# Generated by Django 3.0.8 on 2020-10-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=100)),
                ('Body', models.TextField()),
            ],
        ),
    ]
