# Generated by Django 3.0.8 on 2020-11-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child_Marriages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=100)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Disparity_in_education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=100)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Domestic_violence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=100)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dowry_and_Bride_burning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=100)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inadequate_Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=100)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inferiority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=100)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Low_status_in_the_family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=100)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Selective_abortion_and_female_infanticide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=100)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sexual_harassment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=100)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status_of_widows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=100)),
                ('Body', models.TextField()),
            ],
        ),
    ]
